# Generated by Django 4.2.16 on 2025-03-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_zcompany001_zfiletracker001_zrubrics001_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment101',
            name='is_positive',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Позитивный комментарий'),
        ),
    ]
