# Generated by Django 5.2 on 2025-11-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_zcomment001_published_alter_zcomment001_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='step101',
            name='brands',
            field=models.CharField(default=1, max_length=150, verbose_name='Бренды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step101',
            name='subtitle',
            field=models.CharField(default=1, max_length=150, verbose_name='Подзаголовок'),
            preserve_default=False,
        ),
    ]
