# Generated by Django 4.2.16 on 2025-11-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_step101_data_step10_subtitl_860aa9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step101',
            name='expert_opinion',
            field=models.TextField(blank=True, max_length=11000, verbose_name='Экспертное мнение'),
        ),
        migrations.AlterField(
            model_name='step101',
            name='subtopic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='steps101', to='data.subtopic101', verbose_name='Подтема'),
        ),
        migrations.AlterField(
            model_name='step101',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок title'),
        ),
    ]
