# Generated by Django 4.2.16 on 2025-11-10 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_step101_expert_opinion_alter_step101_subtopic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step101',
            name='author_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps101', to='data.author101', verbose_name='Автор'),
        ),
    ]
