# Generated by Django 4.2.16 on 2025-11-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_comment101_rating_step101_plus_minus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment101',
            options={'ordering': ['-created_date'], 'verbose_name': 'reviews — комменты', 'verbose_name_plural': 'reviews — комменты'},
        ),
        migrations.RemoveField(
            model_name='step101',
            name='expert_opinion',
        ),
        migrations.AddField(
            model_name='author101',
            name='expert_opinion',
            field=models.TextField(blank=True, max_length=11000, verbose_name='Экспертное мнение'),
        ),
        migrations.AddField(
            model_name='author101',
            name='recommends',
            field=models.BooleanField(blank=True, default=False, verbose_name='Рекомендует'),
        ),
        migrations.AddField(
            model_name='comment101',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='comment101',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies101', to='data.comment101', verbose_name='Родительский комментарий'),
        ),
        migrations.AddIndex(
            model_name='comment101',
            index=models.Index(fields=['parent'], name='data_commen_parent__3efb7f_idx'),
        ),
    ]
