# Generated by Django 5.2 on 2025-11-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_comment101_is_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='zcomment001',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Is published'),
        ),
        migrations.AlterField(
            model_name='zcomment001',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
