# Generated by Django 5.2 on 2025-11-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_step101_brands_step101_subtitle'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='step101',
            index=models.Index(fields=['subtitle'], name='data_step10_subtitl_860aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='step101',
            index=models.Index(fields=['brands'], name='data_step10_brands_acc922_idx'),
        ),
    ]
