# Generated by Django 4.2.16 on 2025-11-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_step101_author_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step101',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150, null=True, unique=True, verbose_name='Слуг'),
        ),
    ]
