# Generated by Django 5.2 on 2025-11-16 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_step101_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment101',
            name='rating',
            field=models.PositiveSmallIntegerField(db_index=True, default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (1–5)'),
        ),
        migrations.AddField(
            model_name='step101',
            name='plus_minus',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Плюсы и Минусы'),
        ),
        migrations.AddField(
            model_name='zcomment001',
            name='rating',
            field=models.PositiveSmallIntegerField(db_index=True, default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (1–5)'),
        ),
        migrations.AddField(
            model_name='zcompany001',
            name='plus_minus',
            field=models.TextField(blank=True, default='', verbose_name='Плюсы и Минусы'),
        ),
        migrations.AddIndex(
            model_name='comment101',
            index=models.Index(fields=['rating'], name='data_commen_rating_9423ef_idx'),
        ),
        migrations.AddIndex(
            model_name='zcomment001',
            index=models.Index(fields=['company', 'published', 'created_at'], name='data_zcomme_company_12fb99_idx'),
        ),
        migrations.AddIndex(
            model_name='zcomment001',
            index=models.Index(fields=['rating'], name='data_zcomme_rating_c3f641_idx'),
        ),
    ]
