# Generated by Django 4.2.16 on 2025-11-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_comment101_rating_step101_plus_minus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step101',
            name='expert_recommendation',
            field=models.BooleanField(default=False, verbose_name='Рекомендует'),
        ),
        migrations.AddField(
            model_name='zcompany001',
            name='expert_opinion',
            field=models.TextField(blank=True, default='', max_length=11000, verbose_name='Экспертное мнение'),
        ),
        migrations.AddField(
            model_name='zcompany001',
            name='expert_recommendation',
            field=models.BooleanField(default=False, verbose_name='Рекомендует'),
        ),
    ]
