# Generated by Django 5.2 on 2025-11-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_step101_expert_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step101',
            name='possible_categories',
            field=models.TextField(blank=True, default='', verbose_name='Возможные категории'),
        ),
        migrations.AddField(
            model_name='step101',
            name='possible_tags',
            field=models.TextField(blank=True, default='', verbose_name='Возможные теги'),
        ),
        migrations.AddField(
            model_name='zcompany001',
            name='possible_categories',
            field=models.TextField(blank=True, default='', verbose_name='Возможные категории'),
        ),
        migrations.AddField(
            model_name='zcompany001',
            name='possible_tags',
            field=models.TextField(blank=True, default='', verbose_name='Возможные теги'),
        ),
    ]
