# Generated by Django 5.2 on 2025-11-22 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_step101_possible_categories_step101_possible_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZAuthor001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок title')),
                ('keywords', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ключевые фразы')),
                ('seo_description', models.CharField(blank=True, max_length=350, null=True, verbose_name='Дискрипшн')),
                ('description', models.TextField(blank=True, max_length=11000, verbose_name='Описание')),
                ('h1', models.CharField(max_length=150, verbose_name='Заголовок h1')),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Картинка')),
                ('image_file_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название картинки для файла')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'ZAuthor001',
                'verbose_name_plural': 'ZAuthor001',
            },
        ),
        migrations.AddField(
            model_name='zcompany001',
            name='author_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.zauthor001', verbose_name='Автор экспертного мнения'),
        ),
    ]
