# Generated by Django 4.2.16 on 2025-11-24 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_zauthor001_zcompany001_author_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step101',
            name='subtopic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps101', to='data.subtopic101', verbose_name='Подтема'),
        ),
    ]
