# Generated by Django 4.2.16 on 2025-11-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_step101_subtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment101',
            name='rating',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='zcomment001',
            name='rating',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Лайки'),
        ),
    ]
