# Generated by Django 5.2 on 2026-01-12 00:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_aianalyzeyear_category_expert_investmenttype_market_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='zcomment001',
            name='data_zcomme_company_12fb99_idx',
        ),
        migrations.AddField(
            model_name='zcomment001',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='zcomment001',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='zcomment001',
            name='published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Опубликован'),
        ),
        migrations.AddIndex(
            model_name='zcomment001',
            index=models.Index(fields=['company', 'published', 'published_at'], name='data_zcomme_company_162c20_idx'),
        ),
    ]
